'use client';
import { FormEvent, ReactNode, useEffect, useRef, useState } from 'react';
import { BookOpen, CalendarDays, Check, CheckCheck, ChevronLeft, ChevronRight, Circle, LayoutDashboard, ListTodo, NotebookPen, Plus, TrendingUp, X, ArrowUpRight, Backpack, Pencil, Trash2 } from 'lucide-react';
import { usePlanner } from '@/lib/use-planner';
import { dateKey, Exam, id, localInput, Note, rank, Slot, Task, tomorrow, urgency } from '@/lib/planner';
import { supabase } from '@/lib/supabase/client';
import { appPath } from '@/lib/app-path';
import './planner.css';

const views = [{name:'Overview',icon:LayoutDashboard},{name:'Tasks',icon:ListTodo},{name:'Weekly plan',icon:CalendarDays},{name:'Notebook',icon:NotebookPen},{name:'Exams',icon:BookOpen},{name:'Progress',icon:TrendingUp}] as const;
type ViewName = typeof views[number]['name'];
type Editor = {kind:'task';value:Task}|{kind:'slot';value:Slot}|{kind:'note';value:Note}|{kind:'exam';value:Exam}|null;
const weekDays = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const formatDate = (s:string) => new Date(s).toLocaleString('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});
const emptyTask = ():Task => ({id:id(),title:'',subject:'',due:localInput(tomorrow()).slice(0,11)+'18:00',minutes:25,importance:'Normal',done:null});
const atDate = (current:string,date:Date) => `${dateKey(date)}T${current.slice(11,16)||'18:00'}`;
const quickDates = () => {
  const today = new Date();
  const after = (days:number) => {const date=new Date(today);date.setDate(date.getDate()+days);return date;};
  const friday = (5-today.getDay()+7)%7 || 7;
  return [{label:'Today',date:today},{label:'Tomorrow',date:after(1)},{label:'Friday',date:after(friday)},{label:'Next week',date:after(7)}];
};
function Modal({title,close,children}:{title:string;close:()=>void;children:ReactNode}) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(()=>{ref.current?.showModal(); const d=ref.current; return ()=>d?.close();},[]);
  return <dialog ref={ref} className="p-modal" onCancel={close}><header><h2>{title}</h2><button type="button" onClick={close} aria-label="Close"><X size={22}/></button></header>{children}</dialog>;
}
function Empty({title,action,label}:{title:string;action?:()=>void;label?:string}) {return <div className="p-empty"><Circle size={28}/><strong>{title}</strong>{action&&label&&<button className="p-secondary" onClick={action}><Plus size={18}/>{label}</button>}</div>;}

export default function Planner() {
  const {data,user,ready,busy,error,setError,save,reload}=usePlanner();
  const [view,setView]=useState<ViewName>('Overview'); const [manualDate,setManualDate]=useState(false); const [editor,setEditor]=useState<Editor>(null);
  const [filter,setFilter]=useState('Open'); const [query,setQuery]=useState(''); const [notice,setNotice]=useState('');
  const [account,setAccount]=useState(false); const [email,setEmail]=useState(''); const [sending,setSending]=useState(false);
  const [now,setNow]=useState(Date.now()); const [weekOffset,setWeekOffset]=useState(0);
  useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),60000);return ()=>clearInterval(t);},[]);
  useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),4500);return ()=>clearTimeout(t);},[notice]);
  const open=data.tasks.filter(t=>!t.done).sort((a,b)=>rank(b)-rank(a)||a.due.localeCompare(b.due));
  const today=dateKey(); const nextDay=dateKey(tomorrow());
  const todayTasks=data.tasks.filter(t=>t.due.slice(0,10)===today||t.done&&dateKey(new Date(t.done))===today);
  const finished=todayTasks.filter(t=>t.done).length; const percentage=todayTasks.length?Math.round(finished/todayTasks.length*100):0;
  const nextClasses=data.slots.filter(s=>!s.break&&s.classes[String(tomorrow().getDay())]).sort((a,b)=>a.start.localeCompare(b.start));
  const nextSubjects=new Set(nextClasses.map(s=>s.classes[String(tomorrow().getDay())].toLowerCase()));
  const supplies=data.notes.filter(n=>n.bring&&(!n.subject||nextSubjects.has(n.subject.toLowerCase())));
  const weekStart=new Date();weekStart.setHours(0,0,0,0);weekStart.setDate(weekStart.getDate()-weekStart.getDay()+weekOffset*7);
  const dates=Array.from({length:7},(_,i)=>{const d=new Date(weekStart);d.setDate(d.getDate()+i);return d;});
  const addNote=()=>setEditor({kind:'note',value:{id:id(),title:'',text:'',subject:'',bring:false,packed:null}});
  const addExam=()=>setEditor({kind:'exam',value:{id:id(),title:'',subject:'',date:localInput(tomorrow()),topics:[]}});
  const addSlot=()=>setEditor({kind:'slot',value:{id:id(),label:`Period ${data.slots.filter(s=>!s.break).length+1}`,start:'08:00',end:'08:45',break:false,classes:{}}});
  const primaryAction=view==='Weekly plan'?{label:'Add period',run:addSlot}:view==='Notebook'?{label:'New note',run:addNote}:view==='Exams'?{label:'Add exam',run:addExam}:{label:'New task',run:()=>setEditor({kind:'task',value:emptyTask()})};
  const editorExists=editor?editor.kind==='task'?data.tasks.some(x=>x.id===editor.value.id):editor.kind==='slot'?data.slots.some(x=>x.id===editor.value.id):editor.kind==='note'?data.notes.some(x=>x.id===editor.value.id):data.exams.some(x=>x.id===editor.value.id):false;
  async function toggle(t:Task) { if(await save(s=>{const item=s.tasks.find(x=>x.id===t.id)!;item.done=item.done?null:new Date().toISOString();}))setNotice(t.done?'Task reopened.':'One less thing on your mind. Task complete.'); }
  async function remove(kind: 'tasks'|'notes'|'slots'|'exams',itemId:string) {
    if(!window.confirm('Delete this item? This cannot be undone.'))return;
    if(await save(s=>{if(kind==='tasks')s.tasks=s.tasks.filter(x=>x.id!==itemId);if(kind==='notes')s.notes=s.notes.filter(x=>x.id!==itemId);if(kind==='slots')s.slots=s.slots.filter(x=>x.id!==itemId);if(kind==='exams')s.exams=s.exams.filter(x=>x.id!==itemId);}))setEditor(null);
  }
  const taskRows=(tasks:Task[])=>tasks.length?tasks.map(t=><div className={'p-task '+(t.done?'is-done':'')} key={t.id}>
    <button className="p-check" onClick={()=>void toggle(t)} aria-label={t.done?`Reopen ${t.title}`:`Complete ${t.title}`} aria-pressed={!!t.done}>{t.done?<Check size={18}/>:<Circle size={22}/>}</button>
    <button className="p-task-title" onClick={()=>setEditor({kind:'task',value:structuredClone(t)})}><strong>{t.title}</strong><span>{t.subject||'General'} · {t.minutes} min</span></button>
    <div className="p-task-due"><span className={'p-badge level-'+urgency(t,now).level}>{urgency(t,now).label}</span><time>{formatDate(t.due)}</time></div>
    {t.importance==='High'&&<span className="p-high" title="High importance">!</span>}
  </div>):<Empty title="No tasks here" label="Create a task" action={()=>setEditor({kind:'task',value:emptyTask()})}/>;
  const workload=<section className="p-panel"><div className="p-section-title"><h2>Workload</h2><div className="p-week-control"><button onClick={()=>setWeekOffset(weekOffset-1)} aria-label="Previous week"><ChevronLeft size={20}/></button><span>{dates[0].toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</span><button onClick={()=>setWeekOffset(weekOffset+1)} aria-label="Next week"><ChevronRight size={20}/></button></div></div><div className="p-bars">{dates.map(d=>{const tasks=open.filter(t=>t.due.slice(0,10)===dateKey(d));const mins=tasks.reduce((n,t)=>n+t.minutes,0);const max=Math.max(60,...dates.map(day=>open.filter(t=>t.due.slice(0,10)===dateKey(day)).reduce((n,t)=>n+t.minutes,0)));return <div key={dateKey(d)} className={dateKey(d)===today?'current':''}><span>{mins}m</span><div className="p-bar-track"><div style={{height:`${mins/max*100}%`}}/></div><strong>{d.toLocaleDateString('en-US',{weekday:'short'})}</strong><small>{tasks.length||'—'}</small></div>;})}</div></section>;
  const tomorrowPanel=<section className="p-panel p-tomorrow"><div className="p-section-title"><div><span className="p-eyebrow">{tomorrow().toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric'}).toUpperCase()}</span><h2>Tomorrow</h2></div><Backpack size={26}/></div><h3>Classes</h3>{nextClasses.length?nextClasses.map(s=><div className="p-next" key={s.id}><time>{s.start}</time><strong>{s.classes[String(tomorrow().getDay())]}</strong></div>):<button className="p-empty-action" onClick={()=>setView('Weekly plan')}><Plus size={17}/>Add timetable</button>}<h3>Due</h3>{open.filter(t=>t.due.slice(0,10)===nextDay).map(t=><button key={t.id} className="p-link-row" onClick={()=>setEditor({kind:'task',value:structuredClone(t)})}>{t.title}<ArrowUpRight size={16}/></button>)}{!open.some(t=>t.due.slice(0,10)===nextDay)&&<button className="p-empty-action" onClick={()=>setEditor({kind:'task',value:emptyTask()})}><Plus size={17}/>Add task</button>}<h3>Bag</h3>{supplies.length?supplies.map(n=><label className="p-pack" key={n.id}><input type="checkbox" checked={n.packed===nextDay} onChange={()=>void save(s=>{s.notes.find(x=>x.id===n.id)!.packed=n.packed===nextDay?null:nextDay;})}/>{n.title}</label>):<button className="p-empty-action" onClick={()=>setEditor({kind:'note',value:{id:id(),title:'',text:'',subject:'',bring:true,packed:null}})}><Plus size={17}/>Add item</button>}</section>;
  async function sendEmail(e:FormEvent){e.preventDefault();const client=supabase();if(!client){setError('Cloud sign-in is not configured on this deployment.');return;}setSending(true);const result=await client.auth.signInWithOtp({email:email.trim(),options:{emailRedirectTo:`${location.origin}${appPath('auth/callback/')}`}});setSending(false);if(result.error)setError(result.error.message);else setNotice('Check your email for your sign-in link.');}
  return <div className="planner"><aside className="p-sidebar"><a className="p-brand" href={appPath()} aria-label="School home"><span><CheckCheck size={24}/></span>school<span className="p-brand-dot">.</span></a><div className="p-workspace">YOUR WORKSPACE</div><nav>{views.map(v=><button key={v.name} onClick={()=>setView(v.name)} className={view===v.name?'active':''}><v.icon size={20}/><span>{v.name}</span>{v.name==='Tasks'&&<small>{open.length}</small>}</button>)}</nav><button className="p-account" onClick={()=>setAccount(true)}><span className="p-avatar">S</span><span><strong>{user?'Your school space':'Personal workspace'}</strong><small>{user?'Cloud account':'Saved on this device'}</small></span></button></aside>
    <main className="p-main"><header className="p-top"><strong>{view}</strong><div className="p-top-actions"><button onClick={()=>setAccount(true)} aria-label="Open account"><span className="p-avatar">S</span><span>Account</span></button></div><span className="p-save-state" aria-live="polite">{busy?'Saving…':!ready?'Connecting…':user?'Cloud saved':'On this device'}</span></header>
      {error&&<div className="p-error" role="alert">{error}<button onClick={()=>void reload()}>Reload saved data</button></div>}
      {notice&&<div className="p-toast" role="status"><CheckCheck size={18}/>{notice}<button aria-label="Dismiss" onClick={()=>setNotice('')}><X size={16}/></button></div>}
      <fieldset disabled={!ready||busy} className="p-surface"><div className="p-heading"><div><p className="p-eyebrow">{new Date(now).toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'}).toUpperCase()}</p><h1>{view==='Overview'?'Your day':view}</h1></div><button className="p-primary" onClick={primaryAction.run}><Plus size={20}/>{primaryAction.label}</button></div>
      {view==='Overview'&&<><div className="p-summary"><div className="p-ring" style={{'--progress':`${percentage}%`} as React.CSSProperties}><div><strong>{percentage}%</strong><span>today</span></div></div><div><h2>{todayTasks.length&&finished===todayTasks.length?'Done for today':'Today'}</h2><p className="p-muted">{finished} / {todayTasks.length} complete</p></div><div className="p-metric"><strong>{open.length}</strong><span>left</span></div><div className="p-metric"><strong>{open.filter(t=>urgency(t,now).level===4).length}</strong><span>overdue</span></div></div><div className="p-columns"><div><section className="p-panel"><div className="p-section-title"><h2>Up next</h2><button className="p-text" onClick={()=>setView('Tasks')}>View all <ArrowUpRight size={18}/></button></div>{taskRows(open.slice(0,5))}</section>{workload}</div>{tomorrowPanel}</div></>}
      {view==='Tasks'&&<section className="p-panel"><div className="p-filters"><div className="p-segment">{['Open','Completed','All'].map(f=><button key={f} onClick={()=>setFilter(f)} className={filter===f?'active':''}>{f}</button>)}</div><input aria-label="Search tasks" placeholder="Search task or subject…" value={query} onChange={e=>setQuery(e.target.value)}/></div>{taskRows([...data.tasks].filter(t=>(filter==='All'||(filter==='Open'?!t.done:!!t.done))&&`${t.title} ${t.subject}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>rank(b)-rank(a)||a.due.localeCompare(b.due)))}</section>}
      {view==='Weekly plan'&&<><section className="p-panel"><div className="p-section-title"><h2>Timetable</h2><button className="p-secondary" onClick={()=>setEditor({kind:'slot',value:{id:id(),label:`Period ${data.slots.filter(s=>!s.break).length+1}`,start:'08:00',end:'08:45',break:false,classes:{}}})}><Plus size={18}/>Add period</button></div>{data.slots.length?<div className="p-table-scroll"><table className="p-timetable"><thead><tr><th>Time</th>{weekDays.map(d=><th key={d}>{d.slice(0,3)}</th>)}</tr></thead><tbody>{[...data.slots].sort((a,b)=>a.start.localeCompare(b.start)).map(s=><tr key={s.id} className={s.break?'p-break':''}><th><button onClick={()=>setEditor({kind:'slot',value:structuredClone(s)})}><strong>{s.start}–{s.end}</strong><span>{s.label} <Pencil size={12}/></span></button></th>{s.break?<td colSpan={7}>{s.label||'Break'}</td>:weekDays.map((d,i)=><td key={d}><button onClick={()=>setEditor({kind:'slot',value:structuredClone(s)})}>{s.classes[String(i)]||<span className="p-muted">＋</span>}</button></td>)}</tr>)}</tbody></table></div>:<Empty title="Build your timetable" label="Add first period" action={()=>setEditor({kind:'slot',value:{id:id(),label:'Period 1',start:'08:00',end:'08:45',break:false,classes:{}}})}/>}</section>{workload}</>}
      {view==='Notebook'&&<>{data.notes.length?<><div className="p-actions"><button className="p-secondary" onClick={()=>setEditor({kind:'note',value:{id:id(),title:'',text:'',subject:'',bring:false,packed:null}})}><Plus size={18}/>New note</button></div><div className="p-note-grid">{data.notes.map(n=><button className="p-note" key={n.id} onClick={()=>setEditor({kind:'note',value:structuredClone(n)})}><span className="p-eyebrow">{n.subject||'GENERAL'} {n.bring&&'· BRING'}</span><h2>{n.title}</h2><p>{n.text}</p><span className="p-note-edit">Edit <Pencil size={15}/></span></button>)}</div></>:<section className="p-panel"><Empty title="Keep ideas and reminders here" label="Create first note" action={()=>setEditor({kind:'note',value:{id:id(),title:'',text:'',subject:'',bring:false,packed:null}})}/></section>}</>}
      {view==='Exams'&&<>{data.exams.length?<><div className="p-actions"><button className="p-secondary" onClick={()=>setEditor({kind:'exam',value:{id:id(),title:'',subject:'',date:localInput(tomorrow()),topics:[]}})}><Plus size={18}/>Add exam</button></div><div className="p-note-grid">{[...data.exams].sort((a,b)=>a.date.localeCompare(b.date)).map(ex=><section className="p-panel" key={ex.id}><div className="p-section-title"><span className="p-eyebrow">{ex.subject||'EXAM'}</span><button aria-label={`Edit ${ex.title}`} onClick={()=>setEditor({kind:'exam',value:structuredClone(ex)})}><Pencil size={18}/></button></div><h2>{ex.title}</h2><p className="p-muted">{formatDate(ex.date)}</p><progress aria-label={`${ex.title} preparation`} value={ex.topics.filter(t=>t.done).length} max={ex.topics.length||1}/><p className="p-muted">{ex.topics.filter(t=>t.done).length} / {ex.topics.length} ready</p>{[...ex.topics].sort((a,b)=>a.date.localeCompare(b.date)).map(topic=><label className="p-topic" key={topic.id}><input type="checkbox" checked={topic.done} onChange={()=>void save(s=>{const item=s.exams.find(e=>e.id===ex.id)!.topics.find(t=>t.id===topic.id)!;item.done=!item.done;})}/><span>{topic.title}<small>{topic.date}</small></span></label>)}</section>)}</div></>:<section className="p-panel"><Empty title="Plan your next exam" label="Add first exam" action={()=>setEditor({kind:'exam',value:{id:id(),title:'',subject:'',date:localInput(tomorrow()),topics:[]}})}/></section>}</>}
      {view==='Progress'&&<><div className="p-summary"><div className="p-metric"><strong>{data.tasks.filter(t=>t.done).length}</strong><span>tasks completed · all time</span></div><div className="p-metric"><strong>{data.exams.reduce((n,e)=>n+e.topics.filter(t=>t.done).length,0)}</strong><span>topics prepared</span></div></div>{workload}</>}
      </fieldset>
    </main>
    {editor&&<Modal title={editor.kind==='task'?'Task details':editor.kind==='slot'?'Edit timetable period':editor.kind==='note'?'Notebook':'Exam & study plan'} close={()=>setEditor(null)}><form onSubmit={async e=>{e.preventDefault();setError('');const v=editor.value;if('title'in v&&!v.title.trim())return;
      if(editor.kind==='task' && (!Number.isFinite(new Date(editor.value.due).getTime()) || localInput(new Date(editor.value.due)) !== editor.value.due)){setError('Enter a valid deadline as YYYY-MM-DD HH:mm.');return;}
      if(editor.kind==='slot'){const slot=editor.value;if(slot.end<=slot.start){setError('End time must be after start time.');return;}if(data.slots.some(s=>s.id!==slot.id&&s.start<slot.end&&s.end>slot.start)){setError('This period overlaps another period or break.');return;}}
      if(editor.kind==='exam'&&editor.value.topics.some(t=>!t.title.trim()||t.date>editor.value.date.slice(0,10))){setError('Give every topic a title and a study date on or before the exam.');return;}
      if(await save(s=>{if(editor.kind==='task'){const i=s.tasks.findIndex(t=>t.id===editor.value.id);if(i<0)s.tasks.push(editor.value);else s.tasks[i]=editor.value;}if(editor.kind==='slot'){const i=s.slots.findIndex(t=>t.id===editor.value.id);if(i<0)s.slots.push(editor.value);else s.slots[i]=editor.value;}if(editor.kind==='note'){const i=s.notes.findIndex(t=>t.id===editor.value.id);if(i<0)s.notes.push(editor.value);else s.notes[i]=editor.value;}if(editor.kind==='exam'){const i=s.exams.findIndex(t=>t.id===editor.value.id);if(i<0)s.exams.push(editor.value);else s.exams[i]=editor.value;}}))setEditor(null);
    }}><fieldset disabled={busy||!ready}>
      {editor.kind==='task'&&<><label>Task<input required autoFocus value={editor.value.title} placeholder="What needs to be done?" onChange={e=>setEditor({...editor,value:{...editor.value,title:e.target.value}})}/></label><label>Subject<input value={editor.value.subject} placeholder="Mathematics" onChange={e=>setEditor({...editor,value:{...editor.value,subject:e.target.value}})}/></label><div className="p-date-block"><div className="p-field-title"><strong>Deadline</strong><button type="button" className="p-text" onClick={()=>setManualDate(!manualDate)}>{manualDate?'Use picker':'Type it'}</button></div><div className="p-date-presets">{quickDates().map(option=><button type="button" key={option.label} className={editor.value.due.slice(0,10)===dateKey(option.date)?'active':''} onClick={()=>setEditor({...editor,value:{...editor.value,due:atDate(editor.value.due,option.date)}})}>{option.label}<small>{option.date.toLocaleDateString('en-US',{month:'short',day:'numeric'})}</small></button>)}</div>{manualDate?<label className="p-date-manual">Date and time<input required type="text" placeholder="YYYY-MM-DD HH:mm" value={editor.value.due.replace('T',' ')} onChange={e=>setEditor({...editor,value:{...editor.value,due:e.target.value.replace(' ','T')}})}/></label>:<div className="p-form-row"><label>Date<input required type="date" value={editor.value.due.slice(0,10)} onChange={e=>setEditor({...editor,value:{...editor.value,due:`${e.target.value}T${editor.value.due.slice(11,16)||'18:00'}`}})}/></label><label>Time<input required type="time" value={editor.value.due.slice(11,16)} onChange={e=>setEditor({...editor,value:{...editor.value,due:`${editor.value.due.slice(0,10)}T${e.target.value}`}})}/></label></div>}</div><div className="p-form-row"><label>Minutes<input type="number" min={1} max={1440} required value={editor.value.minutes} onChange={e=>setEditor({...editor,value:{...editor.value,minutes:Number(e.target.value)}})}/></label><label>Importance<select value={editor.value.importance} onChange={e=>setEditor({...editor,value:{...editor.value,importance:e.target.value}})}>{['Low','Normal','High'].map(x=><option key={x}>{x}</option>)}</select></label></div></>}
      {editor.kind==='slot'&&<><label>Period name<input required value={editor.value.label} onChange={e=>setEditor({...editor,value:{...editor.value,label:e.target.value}})}/></label><div className="p-form-row"><label>Starts<input required type="time" value={editor.value.start} onChange={e=>setEditor({...editor,value:{...editor.value,start:e.target.value}})}/></label><label>Ends<input required type="time" value={editor.value.end} onChange={e=>setEditor({...editor,value:{...editor.value,end:e.target.value}})}/></label></div><label className="p-pack"><input type="checkbox" checked={editor.value.break} onChange={e=>setEditor({...editor,value:{...editor.value,break:e.target.checked}})}/>This is a break</label>{!editor.value.break&&weekDays.map((day,i)=><label key={day}>{day}<input placeholder="Subject (leave blank for no class)" value={editor.value.classes[String(i)]||''} onChange={e=>setEditor({...editor,value:{...editor.value,classes:{...editor.value.classes,[i]:e.target.value}}})}/></label>)}</>}
      {editor.kind==='note'&&<><label>Title<input required autoFocus value={editor.value.title} onChange={e=>setEditor({...editor,value:{...editor.value,title:e.target.value}})}/></label><label>Subject<input placeholder="Leave blank for all subjects" value={editor.value.subject} onChange={e=>setEditor({...editor,value:{...editor.value,subject:e.target.value}})}/></label><label>Note<textarea rows={6} value={editor.value.text} onChange={e=>setEditor({...editor,value:{...editor.value,text:e.target.value}})}/></label><label className="p-pack"><input type="checkbox" checked={editor.value.bring} onChange={e=>setEditor({...editor,value:{...editor.value,bring:e.target.checked}})}/>Bring to class</label></>}
      {editor.kind==='exam'&&<><label>Exam<input required autoFocus value={editor.value.title} placeholder="Exam name" onChange={e=>setEditor({...editor,value:{...editor.value,title:e.target.value}})}/></label><label>Subject<input value={editor.value.subject} placeholder="Subject" onChange={e=>setEditor({...editor,value:{...editor.value,subject:e.target.value}})}/></label><div className="p-date-block"><strong>Exam date</strong><div className="p-date-presets">{quickDates().slice(1).map(option=><button type="button" key={option.label} className={editor.value.date.slice(0,10)===dateKey(option.date)?'active':''} onClick={()=>setEditor({...editor,value:{...editor.value,date:atDate(editor.value.date,option.date)}})}>{option.label}<small>{option.date.toLocaleDateString('en-US',{month:'short',day:'numeric'})}</small></button>)}</div><div className="p-form-row"><label>Date<input required type="date" value={editor.value.date.slice(0,10)} onChange={e=>setEditor({...editor,value:{...editor.value,date:`${e.target.value}T${editor.value.date.slice(11,16)||'09:00'}`}})}/></label><label>Time<input required type="time" value={editor.value.date.slice(11,16)} onChange={e=>setEditor({...editor,value:{...editor.value,date:`${editor.value.date.slice(0,10)}T${e.target.value}`}})}/></label></div></div><h3>Study topics</h3>{editor.value.topics.map((t,i)=><div className="p-topic-editor" key={t.id}><label>Topic {i+1}<input required value={t.title} onChange={e=>{const topics=structuredClone(editor.value.topics);topics[i].title=e.target.value;setEditor({...editor,value:{...editor.value,topics}});}}/></label><label>Study on<input required type="date" max={editor.value.date.slice(0,10)} value={t.date} onChange={e=>{const topics=structuredClone(editor.value.topics);topics[i].date=e.target.value;setEditor({...editor,value:{...editor.value,topics}});}}/></label><button type="button" aria-label="Remove topic" onClick={()=>setEditor({...editor,value:{...editor.value,topics:editor.value.topics.filter(x=>x.id!==t.id)}})}><X size={18}/></button></div>)}<button type="button" className="p-secondary" onClick={()=>setEditor({...editor,value:{...editor.value,topics:[...editor.value.topics,{id:id(),title:'',date:today<=editor.value.date.slice(0,10)?today:editor.value.date.slice(0,10),done:false}]}})}><Plus size={16}/>Add topic</button></>}
      {error&&<p className="p-error" role="alert">{error}</p>}<footer>{editorExists?<button type="button" className="p-danger" onClick={()=>void remove(editor.kind==='task'?'tasks':editor.kind==='slot'?'slots':editor.kind==='note'?'notes':'exams',editor.value.id)}><Trash2 size={17}/>Delete</button>:<button type="button" className="p-secondary" onClick={()=>setEditor(null)}>Cancel</button>}<button className="p-primary" type="submit">{busy?'Saving…':'Save'}</button></footer></fieldset></form></Modal>}
    {account&&<Modal title={user?'Your account':'Save across devices'} close={()=>setAccount(false)}>{user?<><p>Your planner is saved to your private account.</p><button className="p-secondary" disabled={busy} onClick={async()=>{const result=await supabase()?.auth.signOut();if(result?.error)setError(result.error.message);else setAccount(false);}}>Sign out</button></>:<form onSubmit={sendEmail}><p>Sign in with an email link to use your cloud planner.</p><label>Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><button className="p-primary" disabled={sending||busy}>{sending?'Sending…':'Send sign-in link'}</button><p className="p-form-help">Device-only and cloud planners are separate. Signing in does not upload or erase your device-only tasks.</p></form>}{error&&<p className="p-error">{error}</p>}{notice&&<p role="status">{notice}</p>}</Modal>}
  </div>;
}
